# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ""  # dataset root dir
train:
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/call/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/dislike/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/fist/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/four/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/like/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/mute/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/ok/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/one/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/palm/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/peace/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/peace_inverted/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/rock/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/stop/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/stop_inverted/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/three/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/three2/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/two_up/train.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/two_up_inverted/train.txt"

val:
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/call/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/dislike/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/fist/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/four/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/like/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/mute/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/ok/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/one/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/palm/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/peace/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/peace_inverted/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/rock/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/stop/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/stop_inverted/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/three/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/three2/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/two_up/val.txt"
  - "cv/panjinquan/dataset/csdn/gesture/HaGRID/trainval/two_up_inverted/val.txt"

test:  # test images (optional)
data_type: voc

# Classes
nc: 19  # number of classes
# names = {"unique": 0}
names: { 'one': 0, 'two_up': 1, 'two_up_inverted': 2, 'three': 3, 'three2': 4,
         'four': 5, 'fist': 6, 'palm': 7, 'ok': 8, 'peace': 9,
         'peace_inverted': 10, 'like': 11, 'dislike': 12, 'stop': 13, 'stop_inverted': 14,
         'call': 15, 'mute': 16, 'rock': 17, 'no_gesture': 18 }
#class_name = {"answer", "tugai", "other"}